image:
  repository: tccr.io/truecharts/qinglong
  pullPolicy: IfNotPresent
  tag: v2.13.1@sha256:a9536995322377a21616c530219917358fdbef985eb9d5866d915dd8bf43627b

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        targetPort: 5700
        port: 10176

persistence:
  data:
    enabled: true
    mountPath: "/ql/data"
