image:
  repository: docker.io/aaronkjones/node-red-custom
  pullPolicy: IfNotPresent
  tag: latest
# See more environment varaibles in the node-red documentation
# https://nodered.org/docs/getting-started/docker
env: {}
  # TZ:
  # NODE_OPTIONS:
  # NODE_RED_ENABLE_PROJECTS:
  # NODE_RED_ENABLE_SAFE_MODE:
  # FLOWS:

service:
  main:
    ports:
      main:
        port: 1880
        targetPort: 1880

persistence:
  data:
    enabled: true
    mountPath: "/data"
