image:
  repository: tccr.io/truecharts/uptime-kuma
  pullPolicy: IfNotPresent
  tag: v1.16.0@sha256:96564e6d523a23fc3454e85c206d1469a91d4040fe6cd848bcf50ba38728245a

securityContext:
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

security:
  PUID: 0

service:
  main:
    ports:
      main:
        port: 3001
        targetPort: 3001

persistence:
  config:
    enabled: true
    mountPath: "/app/data"
